name = "ltpodcast-site"
main = "worker.js"
compatibility_date = "2026-01-01"

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "STOCK_KV"
id = "e9bb1068b9da4ab5952ef3b787558703"
